docusaurus/docs/API/ColorPicker.md, src/components/BrightnessSlider.tsx, src/components/HueSlider.tsx, src/components/OpacitySlider.tsx, src/components/Panel1.tsx, src/components/Panel2.tsx, src/components/SaturationSlider.tsx
Sliders do not work with [the new RNGH web implementation](https://github.com/software-mansion/react-native-gesture-handler/pull/2394) because the new web implementation does not trigger the `onStart` or `onFinish` GH events (or `onCancel` and `onEnd`), so `ColorPicker`'s `onComplete` prop does not fire and the `onActive` callback does not include the `ctx` arg .
On the plus side, the new web implementation _does_ handle the `minDist` prop correctly, allowing the user to click a location in order to update the thumb position without having to drag.
=> fix: use x and y values from onActive handler to support new RNGH web implementation

package-lock.json, src/components/BrightnessSlider.tsx, src/components/HueSlider.tsx, src/components/OpacitySlider.tsx, src/components/Panel1.tsx, src/components/Panel2.tsx, src/components/Panel3.tsx, src/components/SaturationSlider.tsx, src/components/Swatches.tsx, src/types.ts
This PR refactors the color logic out of `onActive` so it can also be applied in `onStart`. As a result, Android and iOS thumbs can have their position updated by tapping instead of having to tap and then drag before the values update.
https://user-images.githubusercontent.com/16565387/222799629-3c7255ac-893e-4cba-97dd-6f66caa5e049.mov
=> set hsva values in onStart

src/components/SaturationSlider.tsx
This fixes the SaturationSlider not responding to brightness in the opaque image area.
=> fix: adaptSpectrum handling in SaturationSlider

docusaurus/docs/API/ColorPicker.md, src/ColorPicker.tsx, src/components/BrightnessSlider.tsx, src/components/HueSlider.tsx, src/components/OpacitySlider.tsx, src/components/Panel1.tsx, src/components/Panel2.tsx, src/components/Panel3.tsx, src/components/SaturationSlider.tsx
This PR migrates the project to React Native Gesture Handler version 2, replacing the old gesture detection methods with the new API. Additionally, it enables the new Web Implementation by default for version 2.6.0 and higher, allowing tap to slide functionality on the Web platform. This update compatibility across platforms.
=> Migrating to RNGH `react-native-gesture-handler` v2 and Enabling the new Web Implementation by default

Example/Example1.tsx, Example/Example2.tsx, Example/Example3.tsx, Example/Example4.tsx, docusaurus/docs/API/_slidersProps.mdx, src/components/Sliders/BrightnessSlider.tsx, src/components/Sliders/HueSlider.tsx, src/components/Sliders/OpacitySlider.tsx, src/components/Sliders/SaturationSlider.tsx, src/types.ts
This pull request adds a new prop called `sliderThickness` to every slider, allowing users to override the global thickness set in the parent component. The new prop is optional and defaults to the value set in the parent component.
=> Add `sliderThickness` prop for individual sliders

docusaurus/docs/API/Panel1.md, docusaurus/docs/API/Panel2.md, docusaurus/docs/API/Panel3.md, docusaurus/docs/API/_slidersProps.mdx, src/components/Panels/Panel1.tsx, src/components/Panels/Panel2.tsx, src/components/Panels/Panel3.tsx, src/components/Sliders/BrightnessSlider.tsx, src/components/Sliders/HueSlider.tsx, src/components/Sliders/OpacitySlider.tsx, src/components/Sliders/SaturationSlider.tsx, src/types.ts
The purpose of this prop is to allow users to provide a higher quality background image for the sliders and panels. The default assets for the color picker are provided in an uncompressed format in a `Figma` file that can be downloaded from this link: [color picker assets](https://www.figma.com/file/1NAZsgrXejzzDsakZtQyuP/reanimated-color-picker-assets?node-id=0%3A1&t=CZzURph1MOPimwI2-1). You can use these assets as a starting point and scale them up or down as needed to fit your app's design.
=> Image source property

Example/package-lock.json, Example/package.json, Example/src/Panel2Saturation.tsx, Example/src/Panel5Example.tsx, ExampleExpo/package-lock.json, ExampleExpo/package.json, ExampleExpo/src/Panel2Brightness.jsx, ExampleExpo/src/Panel2Saturation.jsx, docusaurus/docs/API/Panel2.mdx, docusaurus/docs/API/Panel4.mdx, package.json, src/components/Panels/Panel2.tsx, src/components/Panels/Panel4.tsx, src/types.ts
- Add a `reverseVerticalChannel` prop to `Panel2` to change the direction of the vertical channel's brightness or saturation, depending on the value of the `verticalChannel` prop.
- Add a `reverseHorizontalChannels` prop to `Panel4` to change the direction of the horizontal channels' brightness and saturation.
=> Add a `reverse` prop to change the direction of the brightness or saturation channel.

docusaurus/docs/API/InputWidget.md, src/components/InputWidget/InputWidget.tsx, src/components/InputWidget/Widgets/HslWidget.tsx, src/components/InputWidget/Widgets/HsvWidget.tsx, src/components/InputWidget/Widgets/HwbWidget.tsx, src/components/InputWidget/Widgets/RgbWidget.tsx, src/types.ts
This PR adds a new prop called `disableAlphaChannel` to the `InputWidget` component in order to allow users to prevent and ignore opacity inputs when selecting a color. This feature was requested by @KxmischesDomi in #32 
The `disableAlphaChannel` prop is a `boolean` value that, when set to true, disables the alpha channel input in the `InputWidget` component, preventing users from setting the opacity of the selected color. This prop provides more flexibility to users who want to limit the available color options and ensure consistent color representations across their application.
This PR also includes updates to the component's documentation to reflect the new `disableAlphaChannel` prop and its usage.
=> Add `disableAlphaChannel` prop to `InputWidget` component

src/components/Panels/Panel5.tsx
Panel5 was assuming the provided color would be a HEX color and was thus trying to preemptively trim the color down to the first 7 characters. This PR allows for colorKit to do all the processing for extracting the HEX initialColor.
=> Allow Panel5 to properly parse initial color

src/colorKit/colorKit.ts
This PR allows the alpha channel on a color to be set to a desired percentage. 
Currently, `setAlpha`, `increaseAlpha`, and `decreaseAlpha` can only set the alpha to 0% or 100% (and not the desired percentage) since `Math.round()` rounds to the nearest integer. It also uses the existing `clampAlpha()` function that clamps the value between 0 and 1 and makes it a 2-digit float.
=> Remove integer rounding from ColorKit alpha methods 

src/ColorPicker.tsx
Ignore value changes when the current color already matches the new color from the value props. This is to address the issue when a state is linked to the value prop in #43
=> Prevent unnecessary updates

docusaurus/docs/API/Preview.md, src/components/Preview.tsx, src/types.ts
Add a prop `disableOpacityTexture` to hide the preview background texture image that appears when the color has an opacity less than 1.
=> Add `disableOpacityTexture` prop and fix opacity texture style for the `Preview` component

src/colorKit/index.ts
This pull request adds a new `boolean` option, `roundValues`, to `colorKit` when obtaining the array or object value from converting a color. The default value is set to `true`, ensuring rounded values. However, when set to `false`, the converted color values remain unrounded. This enhancement is particularly useful for internal `colorKit` usage, providing more accurate results when precision is paramount.
```js
colorKit.RGB('#f0ff').object(false)
```
=> Introducing `roundValues` Option in `colorKit` for Precise Color Conversions

docs/docs/API/Panel3.mdx, src/components/Panels/Panel3/ExtraThumb.tsx, src/components/Panels/Panel3/Panel3.tsx, src/types.ts
This pull request introduces a new feature to the `Panel3` component, enhancing the color picker by adding a `rotate` prop. The `rotate` prop allows users to specify a degree of rotation for the hue circle, This prop is optional, and if provided, it rotates the hue circle accordingly.
=> Add Rotate Prop to `Panel3` Component for Hue Circle Rotation

docs/docs/API/Sliders/Hue/HueCircular.mdx, src/components/Sliders/Hue/HueCircular.tsx, src/types.ts
This pull request introduces a new feature to the `HueCircular` component, enhancing the color picker by adding a `rotate` prop. The `rotate` prop allows users to specify a degree of rotation for the hue circle, This prop is optional, and if provided, it rotates the hue circle accordingly.
=> Add `rotate` Prop to `HueCircular` Component for Hue Circle Rotation

package.json, src/components/Sliders/HSL/LuminanceCircular.tsx, src/components/Sliders/Hue/HueCircular.tsx, src/components/Thumb/BuiltinThumbs/DoubleTriangle.tsx, src/components/Thumb/BuiltinThumbs/Hollow.tsx, src/components/Thumb/BuiltinThumbs/Line.tsx, src/components/Thumb/BuiltinThumbs/Pill.tsx, src/components/Thumb/BuiltinThumbs/Plus.tsx, src/components/Thumb/BuiltinThumbs/Ring.tsx, src/components/Thumb/BuiltinThumbs/TriangleDown.tsx, src/components/Thumb/BuiltinThumbs/TriangleUp.tsx
Allow changing the outer circle background color using `'thumbStyle'` and override both the adaptive and `thumbColor` styles.
=> Fix `"ring"` Thumb Shape `BackgroundColor` Style + Refactor

package.json, src/colorKit/index.ts, src/utils.tsx
This PR addresses a common JavaScript compilation issue caused by the Reanimated Babel plugin. The plugin converts worklet functions to arrow functions, which disrupts function hoisting and leads to runtime errors.
Manually converted all affected worklet functions to arrow functions to ensure compatibility with the Reanimated Babel plugin.
=> Fix JS Compilation Conflict with Reanimated Babel Plugin

package.json, src/components/Panels/Panel5.tsx
This pull request addresses the `(NOBRIDGE) ERROR` in `react-native-gesture-handler` where the `GestureDetector` in `Panel5` fails to detect gestures due to view flattening. By wrapping the child components with `<View collapsable={false}>`, we ensure the views remain in the hierarchy and gesture handling works as intended.
After upgrading to the latest version of `react-native-gesture-handler`, the `GestureDetector` in `Panel5` stopped working correctly. Specifically:
- **Observed Error**: `(NOBRIDGE) ERROR  [react-native-gesture-handler] GestureDetector has received a child that may get view-flattened. To prevent it from misbehaving you need to wrap the child with a <View collapsable={false}> . [Component Stack]`. 
- **Behavior Before**: This issue did not occur in earlier versions of …
=> Fix: Resolve gesture detection issues in Panel5 with latest react-native-gesture-handler

ExampleLatest/src/Panel3HslSaturation.tsx, src/components/Preview.tsx, src/components/PreviewText.tsx
Prevent accessing shared values in Preview components. This causes errors in react-native-reanimated strict mode.
This aspect can be neglected for one warning, but if the color picker value is constantly changing(ex: update the initial value in the **onCompleteJS** callback), a bunch of warnings will pollute the console.
To reproduce this behavior you can copy the changes that I added to the **Panel3HslSaturation.tsx** file to update the initial value.
- Run the **ExampleLatest**
- Open the **Panel3 HSL Saturation** 
- Perform any color change
You should see the warnings in the console. (x6 warnings for each initial color update)
=> Fix: Preview warnings

src/components/Panels/Panel1.tsx, src/components/Panels/Panel2.tsx, src/components/Panels/Panel4.tsx, src/components/Sliders/HSB/BrightnessSlider.tsx, src/components/Sliders/HSB/SaturationSlider.tsx, src/components/Sliders/HSL/HSLSaturationSlider.tsx, src/components/Sliders/HSL/LuminanceSlider.tsx, src/components/Sliders/Hue/HueSlider.tsx, src/components/Sliders/OpacitySlider.tsx, src/components/Sliders/RGB/BlueSlider.tsx, src/components/Sliders/RGB/GreenSlider.tsx, src/components/Sliders/RGB/RedSlider.tsx
Addresses a React Native issue https://github.com/facebook/react-native/issues/18266 where using `transform` with `borderRadius` causes rendering issues on Android API levels 24-28. 
Updated the component to handle this edge case.
=> Fix Transform and Border Radius Issue in Color Picker on Android (API 24-28)

__tests__/colorConversion.test.ts, src/colorKit/index.ts
- See https://github.com/facebook/react-native/commit/676359efd9e478d69ad430cff213acc87b273580
- React Native still doesn't support HWB with an alpha channel `hwb(number number% number% / float)` I opened an issue here https://github.com/facebook/react-native/issues/50583
=> Update HWB color format to comply with React Native `0.79.0`
